### ISSUE TITLE
Can't move attached window

### ISSUE THREAD

**Issue by brunelli** [do-sch/gnome-shell-touchpad-window-move#7]
A window can't be moved when it's attached to another, even though it can be moved with 'Super + drag'.

**Comment by do-sch** [comment]
Moving windows and dialoges with the extension behaves slightly different than the 'Super + drag' method, because touch events are stopped, as soon as a window drag begins. I didn't figure out at least how to prevent this.

It should be fixed now. But I'll be waiting some time until I push it to the extensions store, just for the case a new bug occurs.
